theme: minima
title: What characteristics make an actor's career successful ?
description:
    The primary objective of our analysis is to identify the key factors that contribute to the success of an actor's career.
    To achieve this, we need firstly to establish metrics to evaluate an actor's popularity in the cinematographic field.
    In the first part of our analysis, we develop a popularity score based on two main factors that are the audience opinions on the films
    an actor has participated in and the box office performance of those films.
    In the second part, we create another score that measures the cultural impact of the actor, derived from the number
    of nominations and awards achieved in the Oscars category.
    Next, we aim to analyze the film genres in which actors predominantly work. (TODO Complete this section with more details.)
    In the fourth part, we associate each role played by an actor with a specific persona. We will then investigate which
    of these personas are most commonly linked to success. Additionally, we will explore complementary professions or activities
    often undertaken by actors and determine how these align with their personas.
    Finally, in the last part of the analysis, we use the two popularity scores calculated earlier to evaluate whether factors
    such as family background (parents and spouses), nationality, and educational background influence an actor’s popularity.
    We will also examine whether most actors exclusively work in their home countries or prefer to perform in foreign film production countries.
show_description: False
show_downloads: True
navigation:
  - title: Home
    url: /data_stories.md
