# a map used to clean the countries in the Database (generated with ChatGPT for simplicity)
country_mapping = {
    # Modern countries
    'United States of America': 'United States',
    'Japan': 'Japan',
    'Germany': 'Germany',
    'United Kingdom': 'United Kingdom',
    'Canada': 'Canada',
    'Italy': 'Italy',
    'Russia': 'Russia',
    'Norway': 'Norway',
    'Turkey': 'Turkey',
    'India': 'India',
    "People's Republic of China": 'China',
    'Spain': 'Spain',
    'Namibia': 'Namibia',
    'South Africa': 'South Africa',
    'South Korea': 'South Korea',
    'Taiwan': 'Taiwan',
    'Argentina': 'Argentina',
    'Dominion of India': 'India',
    'British Raj': 'India',
    'Switzerland': 'Switzerland',
    'Poland': 'Poland',
    'Nicaragua': 'Nicaragua',
    'Ireland': 'Ireland',
    'United Kingdom of Great Britain and Ireland': 'United Kingdom',
    'Kingdom of Denmark': 'Denmark',
    'Dominican Republic': 'Dominican Republic',
    'Nigeria': 'Nigeria',
    'Haiti': 'Haiti',
    'Venezuela': 'Venezuela',
    'Czech Republic': 'Czech Republic',
    'France': 'France',
    'Australia': 'Australia',
    'Uruguay': 'Uruguay',
    'Mexico': 'Mexico',
    'Philippines': 'Philippines',
    'Sweden': 'Sweden',
    "Polish People's Republic": 'Poland',
    'Serbia': 'Serbia',
    'Pakistan': 'Pakistan',
    'Colombia': 'Colombia',
    'Kingdom of the Netherlands': 'Netherlands',
    'Austria': 'Austria',
    'Guyana': 'Guyana',
    'New Zealand': 'New Zealand',
    'Austria-Hungary': 'Austria',
    'Singapore': 'Singapore',
    'Hong Kong': 'China',
    'Croatia': 'Croatia',
    'Lebanon': 'Lebanon',
    'West Germany': 'Germany',
    'Belgium': 'Belgium',
    'Romania': 'Romania',
    'Greece': 'Greece',
    'Hungary': 'Hungary',
    'England': 'United Kingdom',
    'Chile': 'Chile',
    'Finland': 'Finland',
    'Wales': 'United Kingdom',
    'Socialist Federal Republic of Yugoslavia': 'Serbia',
    'North Macedonia': 'North Macedonia',
    'Slovenia': 'Slovenia',
    'Honduras': 'Honduras',
    'Bosnia and Herzegovina': 'Bosnia and Herzegovina',
    'Iran': 'Iran',
    'Portugal': 'Portugal',
    'Brazil': 'Brazil',
    'Albania': 'Albania',
    'Cuba': 'Cuba',
    'Thailand': 'Thailand',
    'Egypt': 'Egypt',
    'Malaysia': 'Malaysia',
    'Puerto Rico': 'United States',
    'Czechoslovakia': 'Czech Republic',
    'Slovakia': 'Slovakia',
    'Lithuania': 'Lithuania',
    'Kingdom of Bavaria': 'Germany',
    'British Hong Kong': 'China',
    'Sri Lanka': 'Sri Lanka',
    'Republic of China (1912–1949)': 'China',
    'Weimar Republic': 'Germany',
    'Scotland': 'United Kingdom',
    'Kingdom of Yugoslavia': 'Serbia',
    'German Democratic Republic': 'Germany',
    'Algeria': 'Algeria',
    'Russian Socialist Federative Soviet Republic': 'Russia',
    'Russian Soviet Federative Socialist Republic': 'Russia',
    'Russian Republic': 'Russia',
    'The Bahamas': 'Bahamas',
    'Eswatini': 'Eswatini',
    'Bangladesh': 'Bangladesh',
    'Kingdom of Hungary': 'Hungary',
    'Israel': 'Israel',
    'Second Polish Republic': 'Poland',
    'Korea': 'South Korea',
    'Cameroon': 'Cameroon',
    'Syria': 'Syria',
    'Cambodia': 'Cambodia',
    'German Empire': 'Germany',
    'Suriname': 'Suriname',
    'Estonia': 'Estonia',
    'Far Eastern Republic': 'Russia',
    'Union of South Africa': 'South Africa',
    'Gabon': 'Gabon',
    'United Arab Emirates': 'United Arab Emirates',
    'Indonesia': 'Indonesia',
    'Independent State of Croatia': 'Croatia',
    'German Reich': 'Germany',
    'Latvia': 'Latvia',
    'Panama': 'Panama',
    'Georgia': 'Georgia',
    'Uganda': 'Uganda',
    'Ukraine': 'Ukraine',
    'State of Palestine': 'Palestine',
    'Nepal': 'Nepal',
    'Guatemala': 'Guatemala',
    'Morocco': 'Morocco',
    'English people': 'United Kingdom',
    'Belarus': 'Belarus',
    'Nazi Germany': 'Germany',
    'Vietnam': 'Vietnam',
    'Luxembourg': 'Luxembourg',
    'Jamaica': 'Jamaica',
    'Myanmar': 'Myanmar',
    'Peru': 'Peru',
    'Uzbekistan': 'Uzbekistan',
    'State of Malta': 'Malta',
    'Crown Colony of Malta': 'Malta',
    'Malta': 'Malta',
    'Kingdom of Romania': 'Romania',
    'Armenia': 'Armenia',
    'Ethiopia': 'Ethiopia',
    'Yugoslavia': 'Serbia',
    'Federal Republic of Yugoslavia': 'Serbia',
    'Bolivia': 'Bolivia',
    'Bulgaria': 'Bulgaria',
    'Serbia and Montenegro': 'Serbia',
    'Iceland': 'Iceland',
    'Moldova': 'Moldova',
    'Barbados': 'Barbados',
    'China': 'China',
    'Senegal': 'Senegal',
    'Jordan': 'Jordan',
    'El Salvador': 'El Salvador',
    'Qing dynasty': 'China',
    "Hungarian People's Republic": 'Hungary',
    'Tunisia': 'Tunisia',
    'Sudan': 'Sudan',
    'Mauritania': 'Mauritania',
    'Federation of Malaya': 'Malaysia',
    'Benin': 'Benin',
    'Kingdom of Serbs, Croats and Slovenes': 'Serbia',
    'Sierra Leone': 'Sierra Leone',
    'Cyprus': 'Cyprus',
    'Newfoundland Colony': 'Canada',
    'Azerbaijan': 'Azerbaijan',
    "People's Republic of Bulgaria": 'Bulgaria',
    'Mali': 'Mali',
    "Ukrainian People's Republic": 'Ukraine',
    'Costa Rica': 'Costa Rica',
    'Bhutan': 'Bhutan',
    'Ecuador': 'Ecuador',
    'Iroquois': 'United States',
    'Kurdistan': 'Kurdistan',
    'Burkina Faso': 'Burkina Faso',
    'Kosovo': 'Kosovo',
    'North German Confederation': 'Germany',
    'Sultanate of Egypt': 'Egypt',
    'Kingdom of Egypt': 'Egypt',
    'Ottoman Empire': 'Turkey',
    'Trinidad and Tobago': 'Trinidad and Tobago',
    'Taiwan under Japanese rule': 'Taiwan',
    'Northern Cyprus': 'Cyprus',
    'Kenya': 'Kenya',
    'Cape Verde': 'Cape Verde',
    'Cisleithania': 'Austria',
    'Kingdom of Hawaiʻi': 'Hawaii',
    'Republic of Vietnam': 'Vietnam',
    'Isle of Man': 'United Kingdom',
    'South Sudan': 'South Sudan',
    'Ghana': 'Ghana',
    'Czechoslovak Socialist Republic': 'Czech Republic',
    'First Czechoslovak Republic': 'Czech Republic',
    'Somalia': 'Somalia',
    'Ivory Coast': 'Ivory Coast',
    'French protectorate of Tunisia': 'Tunisia',
    'Ukrainian State': 'Ukraine',
    'Republic of Egypt': 'Egypt',
    'United Arab Republic': 'Egypt',
    'Democratic Republic of Georgia': 'Georgia',
    'Korean Empire': 'North Korea',
    'Ukrainian Soviet Socialist Republic': 'Ukraine',
    "Luhansk People's Republic": 'Ukraine',
    'Afghanistan': 'Afghanistan',
    'Brunei': 'Brunei',
    'Pahlavi Iran': 'Iran',
    'The Gambia': 'Gambia',
    'Captaincy General of Catalonia': 'Spain',
    'Tibet': 'China',
    'Zimbabwe': 'Zimbabwe',
    'Pahlavi dynasty': 'Iran',
    'Rosebud Indian Reservation': 'United States',
    'Kingdom of Portugal': 'Portugal',
    'Grenada': 'Grenada',
    'Paraguay': 'Paraguay',
    'Chad': 'Chad',
    'Irish Free State': 'Ireland',
    'Mozambique': 'Mozambique',
    'Beiyang Government': 'China',
    'Belize': 'Belize',
    'Iraq': 'Iraq',
    'Fiji': 'Fiji',
    'Kingdom of Sardinia': 'Italy',
    "Donetsk People's Republic": 'Ukraine',
    'Samoa': 'Samoa',
    'Mandatory Palestine': 'Israel',
    'Bengal': 'India',
    "Tuvan People's Republic": 'Russia',
    'Kyrgyzstan': 'Kyrgyzstan',
    'Rwanda': 'Rwanda',
    'Guinea': 'Guinea',
    'Republic of the Congo (Léopoldville)': 'Congo',
    'Belgian Congo': 'Democratic Republic of the Congo',
    'Democratic Republic of the Congo': 'Democratic Republic of the Congo',
    'Republic of the Congo': 'Republic of the Congo',
    'Montenegro': 'Montenegro',
    'Catalan Countries': 'Spain',
    'Kazakhstan': 'Kazakhstan',
    'Mongolia': 'Mongolia',
    'Grand Principality of Finland': 'Finland',
    'Equatorial Guinea': 'Equatorial Guinea',
    'Republic of Bosnia and Herzegovina': 'Bosnia and Herzegovina',
    'Eritrea': 'Eritrea',
    'Saudi Arabia': 'Saudi Arabia',
    'Dominica': 'Dominica',
    'Georgian Soviet Socialist Republic': 'Georgia',
    'Laos': 'Laos',
    'Papua New Guinea': 'Papua New Guinea',
    'Kingdom of Bohemia': 'Czech Republic'
}
